### PR TITLE
Fix settings icon color

### PR DESCRIPTION
**Pull request by somebody1234**

### CODE REVIEW

**Comment by shu8** [comment]
@somebody1234 thanks for the pull request! But I can't see exactly where this colour change is happening....? 

Doesn't [this line](https://github.com/soscripted/sox/blob/dev/sox.dialog.js#L185) already change the colour to `858c93`?:

**Comment by somebody1234** [comment]
@shu8 Not sure, maybe, but I have a userstyle as well which is changing the color of all text, this fixes it for me.

**Comment by shu8** [comment]
@somebody1234 maybe adding `!important` would fix it for you? I've added it locally and I'll ping you in when it's pushed to dev so you can test it out :)

**Comment by somebody1234** [comment]
@shu8 Wait a second, I can try adding the style locally

**Comment by shu8** [comment]
@somebody1234 can you not change `#soxSettingsButton`'s style to `style="color: #858c93 !important"`?

**Comment by somebody1234** [comment]
@shu8 I can, it does nothing though

**Comment by shu8** [comment]
@somebody1234 weird.. I would have expected it to work. 

However, there's no harm in adding the line you've suggested, so I might as well add it. I've made a few changes locally, so I'm going to add this one in manually as well! Sorry for not just merging these... I just want to try avoid merge conflicts, because they get confusing real quick :P

**Comment by somebody1234** [comment]
@shu8  Okay, thanks! (BTW, relevant mailing-list post about merges [here](http://marc.info/?l=linux-kernel&m=139033182525831) :P)

**Comment by shu8** [comment]
@somebody1234 added in [latest dev version](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

**Pull request closed without merging**
