### PR TITLE
Fix chat title renaming

### PR DESCRIPTION
**Pull request by somebody1234**

### CODE REVIEW

**Comment by shu8** [comment]
@somebody1234 Thanks! I'll manually add this to the dev version, because the pull request is for the master branch, which would cause unnecessary merge conflicts later on

**Comment by somebody1234** [comment]
@shu8 Whoops, sorry, didn't notice I edited the one on the master branch.

**Comment by shu8** [comment]
@somebody1234 no problem, I've added it locally and I'll ping you when it's been pushed to dev :)

**Comment by shu8** [comment]
@somebody1234 added in [latest dev version](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

**Pull request closed without merging**
